### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by tlacroix**
* Added test for HTTP/2 support in cURL
* Added info on how to find and install the AAA certificate required from March 29, 2021
* Added the topic to the simple example
* Added a more complex example, with token format validation, topic discovery, and sample error detection/handling

### CODE REVIEW

**Comment by tlacroix** [comment]
It should help a bit to resolve the multiple issues mentioned here: https://github.com/gepo/apns-http2/issues/3

**Comment by gepo** [comment]
@tlacroix awesome, thank you. I prefer to have links to the Apple website instead of a third party, https://developer.apple.com/news/?id=7gx0a2lp seems a valid link for what you wrote. Change it please and I'll merge it.

I'm looking at what you do with the ```topic``` - extraction from the cert and substitution to the message. It seems that it is better to be part of the library than like this, what do you think?

**Comment by tlacroix** [comment]
@gepo I made the change for the link, and two other minor ones.

As for the topic: yes, it could be nice to try to do it before sending the APN if none was set by the caller and if the `openssl_x509_parse` is available. I wouldn't do it otherwise though. I came to it because I'm using the same code to send APNs on multiple projects, and I wanted to avoid adding an extra parameter in all my `.env`.

A huge thanks for your library by the way, I was in a rush to switch to the HTTP/2 protocol before the deadline tomorrow and it kind of saved my life. Apple is deprecating the binary protocol used by most other libraries, I'm sensing your library will get more and more exposure in the upcoming weeks.

**Comment by gepo** [comment]
great, thanks @tlacroix

**Pull request merged**
